version: '3'

services:
  back:
    build: ./back
    image: kawaiimelnik/draw:back
    restart: always
    ports:
      - 8000:8000

  front:
    build: ./front
    image: kawaiimelnik/draw:front
    depends_on:
      - back
    restart: always
    ports:
      - 80:80